name: Non-Nix Build Test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04 - Clang 18
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y clang-18 clang++-18 cmake ninja-build
        
    - name: Set up Clang 18
      run: |
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
        
    - name: Verify compiler
      run: |
        clang++ --version
        echo '#include <print>' | clang++ -std=c++23 -E - || echo "C++23 print not available"
        
    - name: Bootstrap vcpkg
      run: ./setup-vcpkg.sh
      
    - name: Configure CMake
      env:
        CC: clang-18
        CXX: clang++-18
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja
          
    - name: Build
      run: cmake --build build --parallel
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

  test-macos:
    runs-on: macos-14
    name: macOS 14 - Apple Silicon
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Verify Apple Silicon architecture
      run: |
        echo "System architecture: $(uname -m)"
        echo "Hardware platform: $(uname -p)"
        sysctl -n machdep.cpu.brand_string
        if [ "$(uname -m)" != "arm64" ]; then
          echo "❌ Expected Apple Silicon (arm64) but got $(uname -m)"
          exit 1
        fi
        echo "✅ Running on Apple Silicon (arm64)"
        
    - name: Install dependencies
      run: |
        brew install llvm cmake ninja
        
    - name: Set up LLVM
      run: |
        echo "/opt/homebrew/opt/llvm/bin" >> $GITHUB_PATH
        
    - name: Verify compiler
      run: |
        clang++ --version
        echo '#include <print>' | clang++ -std=c++23 -E - || echo "C++23 print not available"
        
    - name: Bootstrap vcpkg
      run: ./setup-vcpkg.sh
      
    - name: Configure CMake
      env:
        CC: /opt/homebrew/opt/llvm/bin/clang
        CXX: /opt/homebrew/opt/llvm/bin/clang++
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja
          
    - name: Build
      run: cmake --build build --parallel
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

  test-windows:
    runs-on: windows-2022
    name: Windows 2022 - MSVC 2022
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2
      
    - name: Bootstrap vcpkg
      run: .\setup-vcpkg.bat
      shell: cmd
      
    - name: Configure CMake
      run: |
        cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DCMAKE_BUILD_TYPE=Release `
          -G "Visual Studio 17 2022"
          
    - name: Build
      run: cmake --build build --config Release --parallel
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -C Release

  test-compatibility:
    runs-on: ubuntu-22.04
    name: Compatibility Test - Ubuntu 22.04
    continue-on-error: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install available compiler
      run: |
        sudo apt update
        sudo apt install -y clang cmake ninja-build
        
    - name: Check compiler capabilities
      run: |
        clang++ --version
        echo "Testing C++23 support..."
        echo '#include <print>' | clang++ -std=c++23 -E - 2>&1 || echo "C++23 print not available"
        echo "This test demonstrates the need for modern compilers"
        
    - name: Bootstrap vcpkg
      run: ./setup-vcpkg.sh
      
    - name: Configure CMake (expected to fail on older compilers)
      continue-on-error: true
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja
          
    - name: Build (if configure succeeded)
      continue-on-error: true
      run: cmake --build build --parallel
